version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/your-username/your-repo-name"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "govet"
enabled = true

[[analyzers]]
name = "golint"
enabled = true
