name: DeepSource Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18' # Use your project's Go version

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Run DeepSource Analyze
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: ./bin/deepsource run --dsn $DEEPSOURCE_DSN
