name: DeepSource
on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'  # Use the Go version your project requires

    - name: Install DeepSource CLI
      run: curl https://deepsource.io/cli | sh

    - name: Analyze with DeepSource
      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      run: ./bin/deepsource analyze --coverage-file cover.out
