name: DeepSource Analysis

on: [push, pull_request]

jobs:
  analyze:
    name: Run DeepSource Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3

      - name: Install DeepSource CLI
        run: |
          curl https://deepsource.io/cli | sh

      - name: Run DeepSource analysis
        run: deepsource report --analyzer go --directory .
