name: Run DeepSource Analysis

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download DeepSource CLI
        run: |
          wget -q https://deepsource.io/cli/linux/deepsource -O deepsource
          chmod +x deepsource

      - name: Run DeepSource analysis
        run: ./deepsource report --analyzer go
